services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres
    environment:
      POSTGRES_DB: mediatheksync
      POSTGRES_USER: mediatheksync
      POSTGRES_PASSWORD: mediatheksync
    ports:
      - 5432:5432
volumes:
  postgres-data: null