name: 'Build App'

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                path: mediathek-sync
            - uses: actions/checkout@v4
              with:
                repository: fuchsrot/mediathek-sync-ui
                path: mediathek-sync-ui
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - run: npm --prefix ./mediathek-sync ci
            - run: npm --prefix ./mediathek-sync run build
            - run: npm --prefix ./mediathek-sync-ui ci
            - run: npm --prefix ./mediathek-sync-ui run build